### ISSUE TITLE
did-auth-with-react example 获取二维码失败

### ISSUE THREAD

**Issue by jonathanlu813** [ArcBlock/did-connect-examples#4]
修改一下变量后，yarn start 运行例子
```
const appDid = "zNKnvBkatBQF3DW4fDBhec3fhVn9g8sA2ijo";
const serviceHost = "https://connect.wallet.arcblockio.cn";
```
点击login，弹窗中会显示“Request new qrcode failed”，查看console中，显示请求 https://connect.wallet.arcblockio.cn/api/agent/zNKnvBkatBQF3DW4fDBhec3fhVn9g8sA2ijo/profile/token? 失败，错误是 `{"error":{"code":4006,"message":"Invalid token"}}`

**Comment by wangshijun** [comment]
sync 解决了
